version: "3"
services:
  api:
    build: ./api
    volumes:
      - ./api:/app
      - /app/node_modules
    environment:
      PORT: 8000
    expose:
      - 8000
    ports:
      - '8081:8000'

  web:
    build: ./web
    volumes:
      - ./web:/app
      - /app/node_modules
    ports:
      - 8080:8000
